matrix:
  include:
    - os: linux
      jdk: openjdk8
    - os: linux
      jdk: openjdk10
    - os: linux
      jdk: openjdk11

language: java

sudo: false # faster builds

before_install:
- chmod +x gradlew

git:
  depth: 3
